-- =============================================================================
-- Admin support: atomic product saving and list/report functions for the
-- dashboard.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- Variant option validation moves to a DEFERRED constraint trigger so a
-- product's options and variants can be reorganised freely inside one
-- transaction and are validated once, at commit.
-- ---------------------------------------------------------------------------
drop trigger product_variants_validate_options on public.product_variants;

create or replace function public.validate_variant_options()
returns trigger
language plpgsql
set search_path = ''
as $$
declare
  v public.product_variants;
  v_option_count integer;
  v_given integer;
  v_invalid integer;
begin
  -- Re-read: the row may have changed or been deleted since the event.
  select * into v from public.product_variants where id = new.id;
  if not found then
    return null;
  end if;

  select count(*) into v_option_count from public.product_options where product_id = v.product_id;

  v_given := (v.option1_value_id is not null)::int
           + (v.option2_value_id is not null)::int
           + (v.option3_value_id is not null)::int;

  if v_given <> v_option_count then
    raise exception 'VARIANT_OPTIONS_MISMATCH'
      using detail = format('Product has %s option(s); variant specifies %s.', v_option_count, v_given);
  end if;

  select count(*) into v_invalid
  from (values (1, v.option1_value_id), (2, v.option2_value_id), (3, v.option3_value_id)) as g (pos, value_id)
  where g.value_id is not null
    and not exists (
      select 1
      from public.product_option_values ov
      join public.product_options o on o.id = ov.option_id
      where ov.id = g.value_id and o.product_id = v.product_id and o.position = g.pos
    );

  if v_invalid > 0 then
    raise exception 'VARIANT_OPTION_INVALID';
  end if;

  return null;
end;
$$;

create constraint trigger product_variants_validate_options
  after insert or update on public.product_variants
  deferrable initially deferred
  for each row execute function public.validate_variant_options();

-- Uniqueness checks that must tolerate temporary duplicates while renaming or
-- reordering within a save are deferred to commit too.
alter table public.product_variants drop constraint product_variants_combination_unique;
alter table public.product_variants add constraint product_variants_combination_unique
  unique nulls not distinct (product_id, option1_value_id, option2_value_id, option3_value_id)
  deferrable initially deferred;

alter table public.product_options drop constraint product_options_name_unique;
alter table public.product_options add constraint product_options_name_unique
  unique (product_id, name) deferrable initially deferred;

alter table public.product_option_values drop constraint product_option_values_unique;
alter table public.product_option_values add constraint product_option_values_unique
  unique (option_id, value) deferrable initially deferred;

-- ---------------------------------------------------------------------------
-- Computed column: "Black / M". Usable from PostgREST as ?select=id,variant_title
-- ---------------------------------------------------------------------------
create or replace function public.variant_title(v public.product_variants)
returns text
language sql
stable
set search_path = ''
as $$
  select string_agg(ov.value, ' / ' order by o.position)
  from public.product_option_values ov
  join public.product_options o on o.id = ov.option_id
  where ov.id in (v.option1_value_id, v.option2_value_id, v.option3_value_id);
$$;

-- ---------------------------------------------------------------------------
-- admin_save_product: create or update a product with its options, variants,
-- stock levels and images in ONE transaction.
--
-- SECURITY INVOKER: runs with the caller's own privileges, so RLS and grants
-- still apply on every write. IDs for new rows are generated by the client
-- (so images can be uploaded before the first save); every supplied ID is
-- checked to belong to this product.
--
-- p = {
--   id, name, slug, description, category_id, status, featured, seo_title, seo_description,
--   options:  [{ id, name, values: [{ id, value, swatch_hex }] }],
--   variants: [{ id, option_value_ids: [uuid per option, in option order],
--                sku, price_minor, compare_at_price_minor, is_active, on_hand }],
--   images:   [{ id, storage_path, alt_text, option_value_id, width, height }],
--   primary_image_id
-- }
-- ---------------------------------------------------------------------------
create or replace function public.admin_save_product(p jsonb)
returns uuid
language plpgsql
volatile
security invoker
set search_path = ''
as $$
declare
  v_pid uuid := (p ->> 'id')::uuid;
  v_options jsonb := coalesce(p -> 'options', '[]'::jsonb);
  v_variants jsonb := coalesce(p -> 'variants', '[]'::jsonb);
  v_images jsonb := coalesce(p -> 'images', '[]'::jsonb);
  v_status public.product_status := coalesce(p ->> 'status', 'draft')::public.product_status;
  v_option_count integer := jsonb_array_length(coalesce(p -> 'options', '[]'::jsonb));
  v_opt_ids uuid[] := '{}';
  v_val_ids uuid[] := '{}';
  v_var_ids uuid[] := '{}';
  v_img_ids uuid[] := '{}';
  v_value_ids uuid[];
  v_primary uuid;
  v_current integer;
  r record;
  rv record;
begin
  if not public.is_staff() then
    raise exception 'FORBIDDEN' using errcode = '42501';
  end if;
  if v_pid is null then
    raise exception 'INVALID_ARGUMENT' using detail = 'Product id is required.';
  end if;
  if v_option_count > 3 then
    raise exception 'TOO_MANY_OPTIONS';
  end if;
  if jsonb_array_length(v_variants) > 250 then
    raise exception 'TOO_MANY_VARIANTS';
  end if;
  if jsonb_array_length(v_images) > 20 then
    raise exception 'TOO_MANY_IMAGES';
  end if;

  -- Every supplied id must be new or already belong to this product.
  if exists (
    select 1 from public.product_options o
    where o.product_id <> v_pid
      and o.id in (select (x ->> 'id')::uuid from jsonb_array_elements(v_options) x)
  ) or exists (
    select 1 from public.product_option_values ov
    join public.product_options o on o.id = ov.option_id
    where o.product_id <> v_pid
      and ov.id in (
        select (y ->> 'id')::uuid
        from jsonb_array_elements(v_options) x, jsonb_array_elements(coalesce(x -> 'values', '[]'::jsonb)) y
      )
  ) or exists (
    select 1 from public.product_variants v
    where v.product_id <> v_pid
      and v.id in (select (x ->> 'id')::uuid from jsonb_array_elements(v_variants) x)
  ) or exists (
    select 1 from public.product_images i
    where i.product_id <> v_pid
      and i.id in (select (x ->> 'id')::uuid from jsonb_array_elements(v_images) x)
  ) then
    raise exception 'INVALID_ARGUMENT' using detail = 'An id belongs to a different product.';
  end if;

  -- Product
  insert into public.products as t (
    id, name, slug, description, category_id, status, featured, seo_title, seo_description
  ) values (
    v_pid,
    trim(p ->> 'name'),
    lower(trim(p ->> 'slug')),
    nullif(trim(p ->> 'description'), ''),
    nullif(p ->> 'category_id', '')::uuid,
    v_status,
    coalesce((p ->> 'featured')::boolean, false),
    nullif(trim(p ->> 'seo_title'), ''),
    nullif(trim(p ->> 'seo_description'), '')
  )
  on conflict (id) do update set
    name = excluded.name,
    slug = excluded.slug,
    description = excluded.description,
    category_id = excluded.category_id,
    status = excluded.status,
    featured = excluded.featured,
    seo_title = excluded.seo_title,
    seo_description = excluded.seo_description;

  -- Options and values
  for r in select x.value as opt, x.ordinality as pos from jsonb_array_elements(v_options) with ordinality x loop
    insert into public.product_options as t (id, product_id, name, position)
    values ((r.opt ->> 'id')::uuid, v_pid, trim(r.opt ->> 'name'), r.pos)
    on conflict (id) do update set name = excluded.name, position = excluded.position;
    v_opt_ids := v_opt_ids || (r.opt ->> 'id')::uuid;

    if jsonb_array_length(coalesce(r.opt -> 'values', '[]'::jsonb)) = 0 then
      raise exception 'OPTION_NEEDS_VALUES';
    end if;
    if jsonb_array_length(r.opt -> 'values') > 50 then
      raise exception 'TOO_MANY_VALUES';
    end if;

    for rv in select y.value as val, y.ordinality as pos from jsonb_array_elements(r.opt -> 'values') with ordinality y loop
      insert into public.product_option_values as t (id, option_id, value, swatch_hex, position)
      values (
        (rv.val ->> 'id')::uuid,
        (r.opt ->> 'id')::uuid,
        trim(rv.val ->> 'value'),
        nullif(trim(rv.val ->> 'swatch_hex'), ''),
        rv.pos - 1
      )
      on conflict (id) do update set
        option_id = excluded.option_id,
        value = excluded.value,
        swatch_hex = excluded.swatch_hex,
        position = excluded.position;
      v_val_ids := v_val_ids || (rv.val ->> 'id')::uuid;
    end loop;
  end loop;

  -- Variants
  for r in select x.value as var, x.ordinality as pos from jsonb_array_elements(v_variants) with ordinality x loop
    v_value_ids := array(select jsonb_array_elements_text(coalesce(r.var -> 'option_value_ids', '[]'::jsonb))::uuid);
    if coalesce(array_length(v_value_ids, 1), 0) <> v_option_count then
      raise exception 'VARIANT_OPTIONS_MISMATCH';
    end if;
    if (r.var ->> 'price_minor') is null or (r.var ->> 'price_minor')::bigint < 0 then
      raise exception 'INVALID_PRICE';
    end if;

    insert into public.product_variants as t (
      id, product_id, sku, price_minor, compare_at_price_minor,
      option1_value_id, option2_value_id, option3_value_id, is_active, position
    ) values (
      (r.var ->> 'id')::uuid,
      v_pid,
      nullif(upper(trim(r.var ->> 'sku')), ''),
      (r.var ->> 'price_minor')::bigint,
      nullif(r.var ->> 'compare_at_price_minor', '')::bigint,
      v_value_ids[1], v_value_ids[2], v_value_ids[3],
      coalesce((r.var ->> 'is_active')::boolean, true),
      r.pos - 1
    )
    on conflict (id) do update set
      sku = excluded.sku,
      price_minor = excluded.price_minor,
      compare_at_price_minor = excluded.compare_at_price_minor,
      option1_value_id = excluded.option1_value_id,
      option2_value_id = excluded.option2_value_id,
      option3_value_id = excluded.option3_value_id,
      is_active = excluded.is_active,
      position = excluded.position;
    v_var_ids := v_var_ids || (r.var ->> 'id')::uuid;
  end loop;

  -- Remove what the editor no longer lists (variants first: they reference values)
  delete from public.product_variants where product_id = v_pid and id <> all (v_var_ids);
  delete from public.product_option_values ov
    using public.product_options o
    where ov.option_id = o.id and o.product_id = v_pid and ov.id <> all (v_val_ids);
  delete from public.product_options where product_id = v_pid and id <> all (v_opt_ids);

  -- Stock levels (logged through set_inventory_level)
  for r in select x.value as var from jsonb_array_elements(v_variants) x loop
    if (r.var ->> 'on_hand') is not null then
      select on_hand into v_current from public.inventory where variant_id = (r.var ->> 'id')::uuid;
      if v_current is distinct from (r.var ->> 'on_hand')::integer then
        perform public.set_inventory_level((r.var ->> 'id')::uuid, (r.var ->> 'on_hand')::integer, 'Set in product editor');
      end if;
    end if;
  end loop;

  -- Images
  v_img_ids := array(select (x ->> 'id')::uuid from jsonb_array_elements(v_images) x);
  delete from public.product_images where product_id = v_pid and id <> all (v_img_ids);
  update public.product_images set is_primary = false where product_id = v_pid and is_primary;

  for r in select x.value as img, x.ordinality as pos from jsonb_array_elements(v_images) with ordinality x loop
    if (r.img ->> 'storage_path') not like 'products/' || v_pid::text || '/%' then
      raise exception 'INVALID_IMAGE_PATH';
    end if;
    insert into public.product_images as t (
      id, product_id, storage_path, alt_text, position, option_value_id, width, height
    ) values (
      (r.img ->> 'id')::uuid,
      v_pid,
      r.img ->> 'storage_path',
      nullif(trim(r.img ->> 'alt_text'), ''),
      r.pos - 1,
      nullif(r.img ->> 'option_value_id', '')::uuid,
      nullif(r.img ->> 'width', '')::integer,
      nullif(r.img ->> 'height', '')::integer
    )
    on conflict (id) do update set
      alt_text = excluded.alt_text,
      position = excluded.position,
      option_value_id = excluded.option_value_id;
  end loop;

  v_primary := coalesce(nullif(p ->> 'primary_image_id', '')::uuid, v_img_ids[1]);
  if v_primary is not null then
    if not (v_primary = any (v_img_ids)) then
      raise exception 'INVALID_ARGUMENT' using detail = 'Primary image is not in the image list.';
    end if;
    update public.product_images set is_primary = false where product_id = v_pid and is_primary;
    update public.product_images set is_primary = true where id = v_primary;
  end if;

  -- A published product must be purchasable.
  if v_status = 'active' and not exists (
    select 1 from public.product_variants where product_id = v_pid and is_active
  ) then
    raise exception 'PRODUCT_NEEDS_VARIANT';
  end if;

  return v_pid;
end;
$$;

-- ---------------------------------------------------------------------------
-- Reports
-- ---------------------------------------------------------------------------
create or replace function public.admin_inventory(
  p_search text default null,
  p_filter text default 'all', -- all | low | out
  p_limit integer default 50,
  p_offset integer default 0
)
returns table (
  variant_id uuid,
  product_id uuid,
  product_name text,
  product_status public.product_status,
  variant_title text,
  sku text,
  variant_active boolean,
  on_hand integer,
  reserved integer,
  available integer,
  threshold integer,
  total_count bigint
)
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_default integer;
  v_search text := nullif(trim(coalesce(p_search, '')), '');
begin
  perform public.require_staff();
  select low_stock_threshold into v_default from public.store_settings where id;

  return query
  select * from (
    select
      v.id as v_id,
      p.id as p_id,
      p.name as p_name,
      p.status as p_status,
      public.variant_title(v) as v_title,
      v.sku as v_sku,
      v.is_active as v_active,
      i.on_hand as i_on_hand,
      i.reserved as i_reserved,
      i.on_hand - i.reserved as i_available,
      coalesce(i.low_stock_threshold, v_default) as i_threshold,
      count(*) over () as n
    from public.product_variants v
    join public.products p on p.id = v.product_id
    join public.inventory i on i.variant_id = v.id
    where p.status <> 'archived'
      and (v_search is null or p.name ilike '%' || v_search || '%' or v.sku ilike '%' || v_search || '%')
      and (
        p_filter = 'all'
        or (p_filter = 'low' and i.on_hand - i.reserved <= coalesce(i.low_stock_threshold, v_default))
        or (p_filter = 'out' and i.on_hand - i.reserved <= 0)
      )
  ) s
  order by s.p_name, s.v_title nulls first
  limit least(greatest(p_limit, 1), 200)
  offset greatest(p_offset, 0);
end;
$$;

create or replace function public.admin_low_stock(p_limit integer default 8)
returns table (
  variant_id uuid,
  product_id uuid,
  product_name text,
  variant_title text,
  available integer,
  threshold integer
)
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_default integer;
begin
  perform public.require_staff();
  select low_stock_threshold into v_default from public.store_settings where id;

  return query
  select v.id, p.id, p.name, public.variant_title(v), i.on_hand - i.reserved, coalesce(i.low_stock_threshold, v_default)
  from public.product_variants v
  join public.products p on p.id = v.product_id
  join public.inventory i on i.variant_id = v.id
  where p.status = 'active' and v.is_active
    and i.on_hand - i.reserved <= coalesce(i.low_stock_threshold, v_default)
  order by i.on_hand - i.reserved, p.name
  limit least(greatest(p_limit, 1), 100);
end;
$$;

-- Everyone who has ordered or holds a customer account (staff excluded).
create or replace function public.admin_customers(
  p_search text default null,
  p_limit integer default 50,
  p_offset integer default 0
)
returns table (
  customer_id uuid,
  user_id uuid,
  email text,
  full_name text,
  phone text,
  has_account boolean,
  order_count bigint,
  total_spent_minor bigint,
  last_order_at timestamptz,
  first_seen_at timestamptz,
  total_count bigint
)
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_search text := nullif(trim(coalesce(p_search, '')), '');
begin
  perform public.require_staff();

  return query
  with people as (
    select
      c.id as customer_id,
      coalesce(c.user_id, pr.id) as user_id,
      coalesce(c.email, pr.email) as email,
      coalesce(pr.full_name, c.full_name) as full_name,
      coalesce(pr.phone, c.phone) as phone,
      pr.id is not null as has_account,
      least(c.created_at, pr.created_at) as first_seen_at
    from public.customers c
    full join public.profiles pr on pr.id = c.user_id
    where pr.id is null or pr.role = 'customer'
  )
  select
    pe.customer_id,
    pe.user_id,
    pe.email,
    pe.full_name,
    pe.phone,
    pe.has_account,
    coalesce(o.order_count, 0),
    coalesce(o.total_spent, 0)::bigint,
    o.last_order_at,
    pe.first_seen_at,
    count(*) over ()
  from people pe
  left join lateral (
    select
      count(*) filter (where od.payment_status in ('paid', 'refunded')) as order_count,
      sum(od.total_minor) filter (where od.payment_status = 'paid') as total_spent,
      max(od.created_at) as last_order_at
    from public.orders od where od.customer_id = pe.customer_id
  ) o on true
  where v_search is null
     or pe.email ilike '%' || v_search || '%'
     or pe.full_name ilike '%' || v_search || '%'
     or pe.phone ilike '%' || v_search || '%'
  order by coalesce(o.last_order_at, pe.first_seen_at) desc nulls last
  limit least(greatest(p_limit, 1), 200)
  offset greatest(p_offset, 0);
end;
$$;

-- Staff and admins, for the Team section in settings (admin only).
create or replace function public.admin_team()
returns table (user_id uuid, email text, full_name text, role public.user_role, created_at timestamptz)
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
  perform public.require_admin();
  return query
  select id, profiles.email, profiles.full_name, profiles.role, profiles.created_at
  from public.profiles where profiles.role in ('staff', 'admin')
  order by profiles.role, profiles.email;
end;
$$;

-- Admin: grant a role to an existing account by email.
create or replace function public.admin_set_role_by_email(p_email text, p_role public.user_role)
returns void
language plpgsql
volatile
security definer
set search_path = ''
as $$
declare
  v_id uuid;
begin
  perform public.require_admin();
  select id into v_id from public.profiles where email = lower(trim(p_email));
  if not found then
    raise exception 'USER_NOT_FOUND';
  end if;
  perform public.set_user_role(v_id, p_role);
end;
$$;

grant execute on function public.variant_title(public.product_variants) to anon, authenticated;
grant execute on function public.admin_save_product(jsonb) to authenticated;
grant execute on function public.admin_inventory(text, text, integer, integer) to authenticated;
grant execute on function public.admin_low_stock(integer) to authenticated;
grant execute on function public.admin_customers(text, integer, integer) to authenticated;
grant execute on function public.admin_team() to authenticated;
grant execute on function public.admin_set_role_by_email(text, public.user_role) to authenticated;
grant execute on all functions in schema public to service_role;
